name: Run PDK tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Build Dependencies
        run: |
          apt install -yq build-essential

      - name: Validate
        uses: mysociety/action-pdk@master
        with:
          action: 'validate'

      - name: Start Netbox for Testing
        run: |
          cd spec/functions/netbox
          docker-compose up -d

      - name: Run Unit Tests
        uses: mysociety/action-pdk@master
        with:
          action: 'test unit'
